# https://eslint.org/docs/user-guide/configuring
root: true
parser: babel-eslint

env:
  node: true
  browser: true
  es6: true
  commonjs: true

rules:
  strict: 0
  semi: 0
  indent:
    - error
    - 2
  no-console: 1
  no-undef: 2
  no-empty: 2
  no-var: 2
  no-mixed-spaces-and-tabs: 2